import type { HotelSearchResult } from "@/types/hotel";

export const HOTEL_SEARCH_RESULTS: HotelSearchResult[] = [
  {
    id: 1,
    name: "La sabana sur",
    image: "/img/room1.png",
    location: "123 Main Street, Central Area",
    stars: 4.5,
    price: 40.14,
    isFavorite: false,
  },
  {
    id: 2,
    name: "Los yoses",
    image: "/img/room1.png",
    location: "456 Park Avenue, Downtown",
    stars: 4.8,
    price: 40.14,
    isFavorite: false,
  },
  {
    id: 3,
    name: "Paseo Colón Loft",
    image: "/img/room1.png",
    location: "789 Ocean Drive, Beach Area",
    stars: 4.2,
    price: 40.14,
    isFavorite: false,
  },
  {
    id: 4,
    name: "Heredia Central",
    image: "/img/room1.png",
    location: "321 Mountain View, Uptown",
    stars: 4.6,
    price: 40.14,
    isFavorite: false,
  },
  {
    id: 5,
    name: "Alajuela Heights",
    image: "/img/room1.png",
    location: "654 River Road, Riverside",
    stars: 4.3,
    price: 40.14,
    isFavorite: false,
  },
  {
    id: 6,
    name: "Cartago View",
    image: "/img/room1.png",
    location: "987 Forest Lane, Woodland",
    stars: 4.7,
    price: 40.14,
    isFavorite: false,
  },
];
