import type { HotelListing } from '@/types/hotel';

export const STUB_HOTELS: HotelListing[] = [
  {
    id: '1',
    name: 'La sabana sur',
    address: '329 Calle santos, paseo colón, San José',
    price: 4058,
    bedrooms: 2,
    bathrooms: 1,
    petFriendly: true,
    promoted: true,
    images: [
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
    ],
    category: 'Family',
    location: 'San José',
    owner: { name: 'Alberto Casas', avatar: '/img/person.png' },
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    favorite: false,
    stars: 4.5,
  },
  {
    id: '2',
    name: 'Los yoses',
    address: '329 Calle santos, paseo colón, San José',
    price: 4000,
    bedrooms: 2,
    bathrooms: 1,
    petFriendly: true,
    promoted: false,
    images: [
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
    ],
    category: 'Students',
    location: 'San José',
    owner: { name: 'Alberto Casas', avatar: '/img/person.png' },
    description:
      'Compact apartment near key routes with bright interiors and fast access to the city center.',
    favorite: false,
    stars: 4.8,
  },
  {
    id: '3',
    name: 'Paseo Colón Loft',
    address: '225 Avenida central, paseo colón, San José',
    price: 3980,
    bedrooms: 1,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: [
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
    ],
    category: 'Travelers',
    location: 'San José',
    owner: { name: 'Randall Valenciano', avatar: '/img/person.png' },
    description:
      'Loft-style living with clean finishes, natural light, and walkable access to major amenities.',
    favorite: true,
    stars: 4.2,
  },
  {
    id: '4',
    name: 'Heredia Central',
    address: '101 Calle norte, Heredia centro, Heredia',
    price: 4120,
    bedrooms: 3,
    bathrooms: 2,
    petFriendly: true,
    promoted: true,
    images: [
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
    ],
    category: 'Family',
    location: 'Heredia',
    owner: { name: 'María López', avatar: '/img/person.png' },
    description:
      'Larger family-ready floor plan with flexible living space and strong natural ventilation.',
    favorite: false,
    stars: 4.6,
  },
  {
    id: '5',
    name: 'Alajuela Heights',
    address: '78 Ruta 3, Alajuela, Alajuela',
    price: 3895,
    bedrooms: 2,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: [
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
    ],
    category: 'Travelers',
    location: 'Alajuela',
    owner: { name: 'Luis Salas', avatar: '/img/person.png' },
    description:
      'Quiet rental with a warm palette, ideal for medium stays and airport-adjacent access.',
    favorite: true,
    stars: 4.3,
  },
  {
    id: '6',
    name: 'Cartago View',
    address: '54 Vista real, Cartago, Cartago',
    price: 4215,
    bedrooms: 3,
    bathrooms: 2,
    petFriendly: true,
    promoted: false,
    images: [
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
      '/img/hotel/hotel1.jpg',
    ],
    category: 'Students',
    location: 'Cartago',
    owner: { name: 'Ana Ruiz', avatar: '/img/person.png' },
    description:
      'Balanced shared-living layout with comfortable bedrooms and a practical amenity mix.',
    favorite: false,
    stars: 4.7,
  },
  {
    id: 'hotel-1',
    name: 'Shikara Hotel',
    address: '123 Main Street, Central Area',
    price: 40.14,
    bedrooms: 1,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: ['/img/room1.png'],
    category: 'Travelers',
    location: 'San José',
    owner: { name: 'SafeTrust', avatar: '/img/person.png' },
    description: 'A centrally located hotel stay.',
    favorite: false,
    stars: 4.5,
  },
  {
    id: 'hotel-2',
    name: 'Shikara Hotel',
    address: '456 Park Avenue, Downtown',
    price: 40.14,
    bedrooms: 1,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: ['/img/room1.png'],
    category: 'Travelers',
    location: 'San José',
    owner: { name: 'SafeTrust', avatar: '/img/person.png' },
    description: 'A downtown hotel stay near the city center.',
    favorite: false,
    stars: 4.8,
  },
  {
    id: 'hotel-3',
    name: 'Shikara Hotel',
    address: '789 Ocean Drive, Beach Area',
    price: 40.14,
    bedrooms: 1,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: ['/img/room1.png'],
    category: 'Travelers',
    location: 'Puntarenas',
    owner: { name: 'SafeTrust', avatar: '/img/person.png' },
    description: 'A hotel stay close to the coast.',
    favorite: false,
    stars: 4.2,
  },
  {
    id: 'hotel-4',
    name: 'Shikara Hotel',
    address: '321 Mountain View, Uptown',
    price: 40.14,
    bedrooms: 1,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: ['/img/room1.png'],
    category: 'Travelers',
    location: 'Heredia',
    owner: { name: 'SafeTrust', avatar: '/img/person.png' },
    description: 'A comfortable hotel stay in the uptown district.',
    favorite: false,
    stars: 4.6,
  },
  {
    id: 'hotel-5',
    name: 'Shikara Hotel',
    address: '654 River Road, Riverside',
    price: 40.14,
    bedrooms: 1,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: ['/img/room1.png'],
    category: 'Travelers',
    location: 'Alajuela',
    owner: { name: 'SafeTrust', avatar: '/img/person.png' },
    description: 'A riverside hotel stay with convenient local access.',
    favorite: false,
    stars: 4.3,
  },
  {
    id: 'hotel-6',
    name: 'Shikara Hotel',
    address: '987 Forest Lane, Woodland',
    price: 40.14,
    bedrooms: 1,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: ['/img/room1.png'],
    category: 'Travelers',
    location: 'Cartago',
    owner: { name: 'SafeTrust', avatar: '/img/person.png' },
    description: 'A quiet hotel stay near wooded surroundings.',
    favorite: false,
    stars: 4.7,
  },
];

export const HOTEL_CATEGORIES = ['Family', 'Students', 'Travelers'] as const;

export const HOTEL_LOCATIONS = [
  'San José',
  'Heredia',
  'Alajuela',
  'Cartago',
  'Puntarenas',
  'Guanacaste',
  'Limón',
] as const;

export const BEDROOM_FILTERS = [
  { label: 'All apartments', value: 'all' },
  { label: '1 bedroom', value: '1' },
  { label: '2 bedrooms', value: '2' },
  { label: '3 bedrooms', value: '3' },
] as const;

export function getHotelById(id: string) {
  return STUB_HOTELS.find((hotel) => hotel.id === id) ?? STUB_HOTELS[0];
}

export function getSuggestedHotels(activeId: string) {
  return STUB_HOTELS.filter((hotel) => hotel.id !== activeId).slice(0, 5);
}
